version: '3.5'
services:
  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - fiware_workshop
    expose:
      - "1026"
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    healthcheck:
#      test: curl --fail -s http://orion:1026/version || exit 1
#      interval: 5s

  # Database      
  mongo-db:
    image: mongo:latest
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017
    networks:
      - fiware_workshop
    volumes:
      - mongo-db:/data
#    healthcheck:
#      test: |
#        host=`hostname --ip-address || echo '127.0.0.1'`; 
#        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
#      interval: 5s
        

networks:
  fiware_workshop:
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  mongo-db: ~
